/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './features/__root'

// Create Virtual Routes

const ListRouteLazyImport = createFileRoute('/List')()

// Create/Update Routes

const ListRouteLazyRoute = ListRouteLazyImport.update({
	path: '/List',
	getParentRoute: () => rootRoute,
} as any).lazy(() => import('./features/List/route.lazy').then(d => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
	interface FileRoutesByPath {
		'/List': {
			preLoaderRoute: typeof ListRouteLazyImport
			parentRoute: typeof rootRoute
		}
	}
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([ListRouteLazyRoute])

/* prettier-ignore-end */
